### ISSUE TITLE
[Feature request] Search link text

### ISSUE THREAD

**Issue by narcolepticinsomniac** [ssborbis/ContextSearch-web-ext#117] opened 2018-12-04 06:42 UTC
v1.9.1.2
Chromium 70.0.3538.110

Currently, context menu options are available when unselected links are right-clicked, but they only provide the option to search the actual HREF:

![search result](https://user-images.githubusercontent.com/14100003/49422994-dd371e00-f763-11e8-9848-c4058dd61303.png)

I'm not sure how that's ever useful, but searching link text (without needing to actually select it) comes in very handy IME. If there is some scenario where searching the actual HREF is useful, then maybe you could hook up a pref for it, but I would think switching the default behavior to search link text would make much more sense.

**Comment by ssborbis** [comment] 2018-12-04 11:45
Searching for the href was actually a feature request by another user. I'll add the option.

**Comment by narcolepticinsomniac** [comment] 2018-12-04 12:33
Great news, I appreciate it. I don't see any commits though, anything I could side-load in the meantime?

**Comment by ssborbis** [comment] 2018-12-04 14:31
Note the additions for web_accessible_resources. Needed for quickmenu, toolbar/sidebar, add custom search. If you don't need any of those, you can use the manifest as it is in the repo

```{
	"manifest_version": 2,
	"name": "ContextSearch web-ext",
	"description": "__MSG_extensionDescription__",
	"version": "1.9.3",
	"homepage_url": "https://github.com/ssborbis/ContextSearch-web-ext",
	"default_locale": "en",
	"background": {
		"scripts": [
			"lib/browser-polyfill.min.js",
			"opensearch.js",
			"lib/encoding-indexes.js",
			"lib/encoding.js",
			"defaultEngines.js",
			"bookmarks.js",
			"background.js",
			"searchEngineUtils.js",
			"mozlz4.js",
			"keyTable.js",
			"nodes.js"
		]
	},
	"options_ui": {
		"page": "options.html",
		"open_in_tab": true
	},
	"content_scripts": [
		{
			"matches": [
				"<all_urls>"
			],
			"js": [
				"lib/browser-polyfill.min.js",
				"inject.js",
				"inject_quickmenu.js",
				"opensearch.js",
				"searchEngineUtils.js",
				"inject_customSearch.js",
				"inject_sidebar.js"
			],
			"css": [
				"inject.css",
				"inject_sidebar.css"
			],
			"all_frames": true,
			"match_about_blank": true
		}
	],
	"permissions": [
		"<all_urls>",
		"activeTab",
		"contextMenus",
		"storage",
		"tabs",
		"search"
	],
	"optional_permissions": [
		"bookmarks"
	],
	"icons": {
		"48": "icons/icon48.png"
	},
	"web_accessible_resources": [
		"/quickmenu.html",
		"/customSearch.html",
		"/searchbar.html",
		"/icons/search.png",
		"/icons/crossmark.png"
	],
	"browser_action": {
		"default_title": "ContextSearch",
		"default_icon": "icons/icon48.png"
	}
}
```

**Comment by narcolepticinsomniac** [comment] 2018-12-04 14:35
Nice, thanks again man. Great extension btw.

**Comment by ssborbis** [comment] 2018-12-04 14:37
No prob

**Comment by ssborbis** [comment] 2018-12-04 14:48
I'm seeing some inconsistent behavior with some links where the text is in a child element and not directly attached to an anchor. Let me know if you run into that problem and link me the website. I'm seeing it on Google News now

**Comment by ssborbis** [comment] 2018-12-04 15:09
Added a fix for some links and I may have missed uploading a file required for a lot of chrome functions. You might wan to grab the latest repo just in case.

**Comment by narcolepticinsomniac** [comment] 2018-12-04 23:44
I didn't get a chance to load it and test it till I just got back home. Unfortunately, it doesn't seem to work as expected. The context menu text is reflecting the text content now, but it's still searching the href instead of the text content.

**Comment by ssborbis** [comment] 2018-12-05 00:00
Poop.  Just updated the repo. Should be working now

**Comment by narcolepticinsomniac** [comment] 2018-12-05 00:11
Not quite yet, AFAICT. Not opening at all now. Got a warning and a couple errors:

![warning](https://user-images.githubusercontent.com/14100003/49481297-51230600-f7f8-11e8-8415-028496d22734.png)

![error1](https://user-images.githubusercontent.com/14100003/49481308-554f2380-f7f8-11e8-9c3c-b8ae2b3860e8.png)

![error2](https://user-images.githubusercontent.com/14100003/49481313-597b4100-f7f8-11e8-9fe2-c00149196cdc.png)

**Comment by ssborbis** [comment] 2018-12-05 00:49
Hmm... you're right. It's working in FF but not chrome. There must be some differences in the API I didn't account for. Gimme a few and I'll get something set up.

**Comment by ssborbis** [comment] 2018-12-05 00:55
The "search" in the manifest is a FF-only API. Chrome should work ok with the error.

Yep, no linkText attribute in Chrome. That's a pain. I'll post again when I have a workaround. the `var = searchTerms` error is a result

The widget error is a bit unexpected. That's a new object in the userOptions and should have been imported with some default properties. 

I'll post again when I've got something that works in Chrome

**Comment by narcolepticinsomniac** [comment] 2018-12-05 00:58
Gotta love cross-browser compatibility. =)  No rush, I'll be around for a while. I appreciate the effort. I expected it'd be much simpler.

**Comment by ssborbis** [comment] 2018-12-05 01:03
Nearly there. Got the link code working. Checking on the widget error.

**Comment by ssborbis** [comment] 2018-12-05 01:09
Alright, I tested the fix in Chrome and it's working for me. If you have any more errors with userOptions, you might give a look in Options and check for any selection elements with an empty value. I've got some new code that hasn't been fully tested yet and that might be causing the error. Let me know how the latest push is working for you.

**Comment by narcolepticinsomniac** [comment] 2018-12-05 02:03
LGTM, just the gecko/search warnings. I haven't touched any prefs yet, other than search engines. I'm sure I will though, so I'll check for errors periodically and let you know if I run into any. 

Just decided to check if there were any new options in this extension category yesterday. One of the big things I was looking for was the ability to search link text in custom engines, so now I have one. Previously, I had three separate extensions for selection search, reverse image search, and link text search, and the link text one wasn't configurable with custom engines. You're well on your way to providing every possible aspect of search functionality, which would be pretty sweet.

Only feature I'm keeping a different extension for currently is [this one](https://chrome.google.com/webstore/detail/search-the-current-site/jliolpcnkmolaaecncdfeofombdekjcp) for domain/subdomain specific searches, which come in handy. Also, a somewhat related feature I've never really found would be some kind of convenient toggling for other common parameters, most notably "exact match".

Your extension is the closest to an all-in-one that I've seen though, so keep up the good work.

**Comment by ssborbis** [comment] 2018-12-05 02:15
> Only feature I'm keeping a different extension for currently is this one for domain/subdomain specific searches, which come in handy:

You can do some domain/subdomain site searches already. ContextSearch ships with a google sitesearch engine. You'd have to add the bing / yahoo / yandex engines yourself but the formatting is pretty straightforward. What are you missing in ContextSearch the other addon provides?

> Also, a somewhat related feature I've never really found would be some kind of convenient toggling for other common parameters, most notably "exact match"

Care to elaborate?

**Comment by narcolepticinsomniac** [comment] 2018-12-05 02:34
Yeah, I'm just getting greedy. My laziness knows no bounds. =) The ability to add all the different subdomain params with toggles in the popup is super convenient, and other common params could have similar toggles. That extension defaults to searching the current site though.  Yours doesn't so it'd need an additional toggle to switch to that mode. You've got a ton of room in the popup though, speaking of which, maybe give that poor input a little padding around it. =)

Btw, invoking the context menu in the popup, and using the "element picker", results in a couple errors:

![error1](https://user-images.githubusercontent.com/14100003/49486344-0c08cf00-f80c-11e8-9963-f71c86b9821f.png)

![error2](https://user-images.githubusercontent.com/14100003/49486353-11feb000-f80c-11e8-8190-8291b174d520.png)

**Comment by ssborbis** [comment] 2018-12-05 12:49
> That extension defaults to searching the current site though. Yours doesn't

The google site search included with CS is set up to search the current domain. The Chrome add-on you linked is set up to search ... the current **sub**domain? If that's what you want, that's a simple edit you can do in the search engines manager.  Edit site search and change {domain} to {subdomain} in the template. You could even make a copy as a new engine and then edit, so you'd have both.

> You've got a ton of room in the popup though, speaking of which, maybe give that poor input a little padding around it. =)

Got a screenshot? I wanna be sure we're seeing the same layout. If we are and you want a slightly different look, add a custom css rule in the User Styles at the bottom of the Menus tab in Options. 

```
#searchBarContainer {
   padding: 10px;
}
```

> Btw, invoking the context menu in the popup, and using the "element picker" in devtools, results in a couple errors:

I could reproduce only when multiple menus were open at the same time ( toolbar & sidebar for example ). I'll add a check.

**Comment by hg42** [comment] 2018-12-05 13:12
I don't habe all of the default engines (don't know why).

But defaultEngines.js (last line) contains a `{subdomain}` search called "Google Site Search":

`"https://www.google.com/search?q=site%3A{subdomain}+{searchTerms}&ie=utf-8&oe=utf-8&client=firefox-b-1"`

I used that and it works.

**Comment by narcolepticinsomniac** [comment] 2018-12-05 13:51
>The Chrome add-on you linked is set up to search ... the current subdomain?

It defaults to the whole domain string, like `forum.example.com`. It'll have a toggle for broader searches for `example.com`, and it'll have toggles for narrower searches every step of the string in the current URL, like `forum.example.com/discussions` and `forum.example.com/discussions/development`.

It's functionality is pretty specific, so it depends if you you think it's worthwhile incorporating. There'd be plenty of room to have another "site search" input with string toggles underneath the current popup content if you did, but these aren't trivial features to implement. I did notice `{subdomain}`, which is very cool, just limited comparatively. I'm fine with a separate extension, just figured I'd mention it since you seem to be covering all the other bases for search functionality.

>Got a screenshot?

Sure. All I meant was a little breathing room for the input in the popup. It's so flush with the edges that the input focus outline gets cut off on the sides. 

```
#searchBarContainer {
   padding: 5px;
}
```

Works fine in "User Styles".

Before:

![before](https://user-images.githubusercontent.com/14100003/49516985-0097c100-f869-11e8-9a21-5468667ef163.png)


After:

![after](https://user-images.githubusercontent.com/14100003/49517030-21601680-f869-11e8-9e81-db9468f7faeb.png)

As for the errors when the context menu is invoked in the popup, I reproed a few times in a row yesterday, but can't right now. Must have to do with some another contributing factor, as you mentioned. Not like they really matter anyway, but I figured you'd wanna run a check to prevent them.

**Comment by hg42** [comment] 2018-12-05 13:53
> It could be because the default engines are only included with new profiles

yes, I thought so, but I have engines that "always come back", if I delete them, so I disabled them now (thanks for that possibility, which is useful for other purposes, too!).
But I think, these are defaults of FF, not CS.

I tested on Chrome Version 70.0.3538.110 (Official Build) (64-bit) and everything works, subdomain, domain, and client=firefox... doesn't break the site search.

At one point, I forgot to press "Save" on the engine, which confused me a little bit, because other parts of the settings are immediately used without any save button.

**Comment by hg42** [comment] 2018-12-05 13:57
> It defaults to the whole domain string, like forum.example.com

so, simply change {subdomain} (=forum.example.com
) to {domain} (=example.com)

Di you notice the style issue in sidebar menu or in one of the others? Because sidebar menu is injected into the page, and it's a matter of separating the namespaces. There might be still some holes.

**Comment by ssborbis** [comment] 2018-12-05 14:11
@hg42

> yes, I thought so, but I have engines that "always come back", if I delete them, so I disabled them now (thanks for that possibility, which is useful for other purposes, too!).
But I think, these are defaults of FF, not CS.

Yep, the returning engines are the ones in FF not CS. Might be a good idea to add a button to restore defaults.

> At one point, I forgot to press "Save" on the engine, which confused me a little bit, because other parts of the settings are immediately used without any save button.

Yeah I should probably check for changed values and prompt before closing.

> Did you notice the style issue in sidebar menu or in one of the others? Because sidebar menu is injected into the page, and it's a matter of separating the namespaces. There might be still some holes.

Is that directed at me or narcolepticinsomniac?

**Comment by ssborbis** [comment] 2018-12-05 14:13
> It's functionality is pretty specific, so it depends if you you think it's worthwhile incorporating. There'd be plenty of room to have another "site search" input with string toggles underneath the current popup content if you did, but these aren't trivial features to implement. I did notice {subdomain}, which is very cool, just limited comparatively. I'm fine with a separate extension, just figured I'd mention it since you seem to be covering all the other bases for search functionality.

Adding the functionality is trivial. Getting it to integrate nice with **all** menus is the hard part. Doable, but it will take some thought.

**Comment by hg42** [comment] 2018-12-05 14:17
> Is that directed at me or narcolepticinsomniac?

:-) sorry, narcolepticinsomniac

**Comment by hg42** [comment] 2018-12-05 14:22
@narcolepticinsomniac 

> There'd be plenty of room to have another "site search" input with string toggles underneath

I wouldn't want specialized behavior like this.
Couldn't you create some more search engines to get that specific functionality?
Can you give examples?

**Comment by hg42** [comment] 2018-12-05 14:30
the engines could be arranged in subfolders, which is the way such things can be grouped and this also works with drag and drop.
I am voting for a consistent usage, so instead fo recreating another extension (with different goals and conditions), it should be integrated into the CS way.

**Comment by narcolepticinsomniac** [comment] 2018-12-05 14:34
>I am voting for a consistent usage, so instead of recreating another extension (with different goals and conditions), it should be integrated into the CS way.

I'm not voting for anything. I already have another extension which does exactly what I'm describing. I only made the suggestion to incorporate similar functionality because it seems to be the only thing missing. This extension is pretty great as it is. =)

**Comment by hg42** [comment] 2018-12-05 14:35
btw. I didn't find a list of the available variables when looking in help?
I see (and understand) the help page is not very big :-), but I think, such reference information is most important.

**Comment by ssborbis** [comment] 2018-12-05 14:36
> btw. I didn't find a list of the available variables when looking in help?
I see (and understand) the help page is not very big :-), but I think, such reference information is most important.

I'm dreading overhauling the help section. I've been putting it off for months.

**Comment by hg42** [comment] 2018-12-05 14:40
> I'm not voting for anything

note, I am not voting against the functionality (may be I would use it, too), only searching for ways to integrate it with the whole ui concept (e.g. I use drag and drop very often and wouldn't want an additional click etc.
Btw. do/can you use that site search extension with google only or are there other engines that can do site search (never tried).

**Comment by ssborbis** [comment] 2018-12-05 14:42
> I am voting for a consistent usage, so instead of recreating another extension (with different goals and conditions), it should be integrated into the CS way.

Site searching still feels integral to what CS is trying to provide. If it can be done cleanly, I'll add it. If it's a sloppy fit I won't. I had to pass on a suggestion to add 'copy as markdown' because it was going to get a bit messy in options. Turns out a simple bookmarklet took care of most of the functionality and was able to be used with CS no problem. 

I'll toy around with a few things and check with you both for input.

**Comment by narcolepticinsomniac** [comment] 2018-12-05 14:46
You can switch them in options, but it's not super convenient or highly configurable:

![options](https://user-images.githubusercontent.com/14100003/49520949-56bd3200-f872-11e8-9238-cedf6da69ce4.png)

If I cared to add others, I'd add them myself and side-load it, but I'm fine with Google for these kinds of searches.

**Comment by hg42** [comment] 2018-12-05 14:51
there could be a variable `{site}` that could dynamically popup a context menu with path entries when triggered or hovered (in simple words, I know it is more difficult).
This would work with click **and** drop.

**Comment by ssborbis** [comment] 2018-12-05 14:51
> there could be a variable {site} that could dynamically popup a context menu with path entries when triggered or hovered (in simple words, I know it is more difficult).
This would work with click and drop.

That's exactly what I was thinking

**Comment by ssborbis** [comment] 2018-12-05 14:52
It would leave the {domain} and {subdomain} types alone and add a dynamic type

**Comment by hg42** [comment] 2018-12-05 14:57
This textual context "folder" could be useful for other engines, too. The icon based menu is sometimes difficult, e.g. if you have several google engines, they all share the same icon or you have to draw your own variants, which is inconvenient. A text menu would solved this. So a folder could have an option to display as text menu.
If you would add variables for paths, then it could be put into the search url.
If the title would interpolate variables, too, then it would dynamically change, too.
All this would also work with the normal context menu, which I still use on pages that block CS.

**Comment by hg42** [comment] 2018-12-05 14:59
and the display code should already be there (single column for toolbar menu)

**Comment by ssborbis** [comment] 2018-12-05 15:07
> This textual context "folder" could be useful for other engines, too. The icon based menu is sometimes difficult, e.g. if you have several google engines, they all share the same icon or you have to draw your own variants, which is inconvenient. A text menu would solve this.
So, a folder could have an option to display as text menu.
If you would add variables for paths, then it could be put into the search url.
If the title would interpolate variables, too, then it would dynamically change, too.
All this would also work with the normal context menu, which I still use on pages that block CS.

I'll start there by seeing what it would take to add a display override on a per-folder basis since obviously any site search path would require the menu in single-column format

**Comment by hg42** [comment] 2018-12-05 15:07
btw. this could also implement behavior like "Navigate up WE", "Uppity" etc.

**Comment by hg42** [comment] 2018-12-05 15:13
for a first step:
* add option for folders to display as single column
* add pathN variable(s)

This alone can be used to implement a site search with a fixed number of directories.

An entry that is really a dynamic group of entries would be most advanced.

**Comment by hg42** [comment] 2018-12-05 15:23
I am currently looking into things like http://xiki.org/ (see https://youtu.be/bUR_eUVcABg).
It's amazing, what can be done with such a simple usage pattern.

I see CS does something similar and I think it could even be just as flexible (when introducing plugins).
However, what I wanted to say, the main point is to stick to the simple pattern.

**Comment by ssborbis** [comment] 2018-12-06 14:41
> I am currently looking into things like http://xiki.org/ (see https://youtu.be/bUR_eUVcABg).
It's amazing, what can be done with such a simple usage pattern.

Damn, that is fancy. Next time I dev on linux I'll check that out.

Ok I pushed a workable site search expanding menu. Put a {selectdomain} in any template and it should treat that engine as a special tile. No code for the standard context menu right now, but looks to be working in quick / sidebar / toolbar menus.

Current behavior -  clicking a site search tile opens like a folder showing path options. Uses the .singleColumn class when using tile or labels format.

Plenty of bugs I'm sure but I've got most of the iframe resizing issues worked out (pain in the ass btw)

I've only done minor testing with this google template

`https://www.google.com/search?q=site%3A{selectdomain}+{searchTerms}&ie=utf-8&oe=utf-8&client=firefox-b-1`

but it looks promising

**Comment by hg42** [comment] 2018-12-06 22:02
> Damn, that is fancy. Next time I dev on linux I'll check that out

unfortunately it's in some strange state (e.g. the xiki command doesn't work and is replaced half way by xsh) and installing doesn't work well (you need ruby <= 2.4.4, eventually use rvm or rbenv). But you got the principle...

**Comment by hg42** [comment] 2018-12-06 22:11
> but it looks promising
yepp...nice

> bugs
* doesn't work with drag-and-drop (menu doesn't open, button remains highlighted)
* should the menu close after selection?

**Comment by ssborbis** [comment] 2018-12-06 22:21
> doesn't work with drag-and-drop (menu doesn't open, button remains highlighted)

on the list . no keyboard nav either ( new tile type isn't recognized )

> should the menu close after selection?

??? Choosing a path from the list should give the same behavior as clicking any other search engine. Menu closing determined by options. What are you seeing?

**Comment by narcolepticinsomniac** [comment] 2018-12-06 23:06
Yeah, looks promising. There should also be an option for the base domain if the current URL is a sub. For example `addons.mozilla.org` should have an entry for `mozilla.org`, although it should default to the current sub. 

Also, whether or not the final step in the path is an available option seems to depend on the whether the final forward slash is present. Just noticed that the other extension does that too, but it should really register as an option regardless, minus any hashes. Maybe this is somewhat of a more recent inconsistency though, since IIRC, browsers used to add the final forward slash even if it wasn't shown.

**Comment by ssborbis** [comment] 2018-12-06 23:14
> Yeah, looks promising. There should also be an option for the base domain if the current URL is a sub. For example addons.mozilla.org should have an entry for mozilla.org, although it should default to the current sub.

to keep the layout consistent, I think you want the root domain listed first. It would look odd if it was between the subdomain and the first path. I could set the current subdomain as the 'selected' option in the `#2` spot, but the root domain should probably remain in the `#1` slot

> Also, whether or not the final step in the path is an available option seems to depend on whether the final forward slash is present. Just noticed that the other extension does that too, but it should really register as an option regardless, minus any hashes/params. Maybe this is somewhat of a more recent inconsistency though, since IIRC, browsers used to add the final forward slash even if it wasn't shown.

How to tell a path from a webpage without the trailing slash? Filter out?  *.* ? . Pages without extensions will still get through. Might be worth it though. Something to think about.

**Comment by narcolepticinsomniac** [comment] 2018-12-06 23:31
>I could set the current subdomain as the 'selected' option in the #2 spot, but the root domain should probably remain in the #1 slot

SGTM.

>How to tell a path from a webpage without the trailing slash?

Yeah, regex. Check for and grab any string between the last forward slash and the end of the string, if it exists, then slice to lose any possible hashes/params. You could also ignore any strings with undesirable extensions. Is it more complicated than that?

**Comment by ssborbis** [comment] 2018-12-06 23:35
> Yeah, regex. Check for and grab any string between the last forward slash and the end of the string, if it exists, then slice to lose any possible hashes/params. You could also ignore any strings with undesirable extensions. Is it more complicated than that?

Sure, but I meant how to tell a path /someword minus the trailer slash from a webpage /someword 

Would it even matter if a web page got through?

**Comment by narcolepticinsomniac** [comment] 2018-12-06 23:42
>Would it even matter if a web page got through?

Not really. It'd be pretty useless, but it'll still work. Not like the forward slash is consistent for them either.

**Comment by hg42** [comment] 2018-12-07 00:16
> /someword

I think, if the last part looks like a page or not, doesn't really matter. Even a directory can be a page (rewrite rules etc.).
Some sites use the directory hierarchy to select pages, some use the parameters after the "?". You never know...so you can only offer all.
If it's a document, it's a search inside the page, which might be useful, too.

**Comment by hg42** [comment] 2018-12-07 00:37
> > should the menu close after selection?
> ??? Choosing a path from the list should give the same behavior as clicking any other search engine. Menu closing determined by options. What are you seeing?

I have the same behavior for selectdomain and other folders as expected. But I am not sure if this is what I want. At least I stumbled over it. I expected it to close after the click.
Basically, if the main menu is configured to stay open, this doesn't necessarily mean that sub-menus/sub-folders should stay open, too.
I think this depend on the meaning of the folders. Do you mostly search multiple times from the same folder?
E.g. if I have a "development tools" folder, I may usually want to search via one tool and then via another, so the folder should stay open.
On the other hand, if I have "google" and "bing" folders, I might want to always start from the main menu, because I want to search google maps, then bing maps etc.
This could only be solved by a flag for each folder, which seems to be a bit over-engineered.
However, I guess, I mostly search from a different folder, so for me, folders should probably close after click even if the main menu is always kept open.

**Comment by ssborbis** [comment] 2018-12-07 00:41
@hg42 

That's probably true that you wouldn't normally search more than one path. Simple change. Cleaning up a few things for a new highlighting option and I'll make the change and push.

**Comment by ssborbis** [comment] 2018-12-07 14:06
>  
    bugs

    doesn't work with drag-and-drop (menu doesn't open, button remains highlighted)

Fixed on the next push

**Closed** 2018-12-14 00:03 UTC
