### ISSUE TITLE
[BUG] 1.46.4 sometimes can't save the engine parameters

### ISSUE THREAD

**Issue by 7peanuts** [ssborbis/ContextSearch-web-ext#609] opened 2022-11-22 04:49 UTC
I saved it several times before it succeeded.
Windows 11 22H2 22621.819
Chromium

![-gif-1](https://user-images.githubusercontent.com/82173614/203224182-3a5617a9-b01a-45f6-970c-3465f66e97ec.gif)

**Comment by ssborbis** [comment] 2022-11-22 08:03
I've noticed this too, but not consistently enough to track down the cause.

**Comment by ssborbis** [comment] 2022-11-22 08:07
Also, this may not be an issue after the next release. There are some significant backend changes that could make go away. I haven't seen it while on the newest local code.

**Comment by logusergithub** [comment] 2022-11-22 08:53
I also confirm, thanks. I thought it was a problem limited to me having many search engines. If it helps, as I am currently adding some engines, these are the steps:

- add new engine -> save and close
- reopen the new engine -> insert parameters -> save and close

The first save does not keep the parameters entered, the second one does. From my experience it seems to me that it is limited to when you add (or in the case of the video you copy) a new engine. Since I had no idea until a few days ago how powerful 'Add to ContextSearch' was (it adds engines even with post parameters), I am also  modifying the parameters of some old existing engine and so far the first save seem to works.

PS: I love the new 'save and close'

**Comment by ssborbis** [comment] 2022-11-22 09:04
> PS: I love the new 'save and close'

Thanks. Long overdue.

Next release has cut / paste to move engines around easier on long lists

**Comment by simonbcn** [comment] 2023-07-06 18:01
Same problem on Brave on Linux.
extension version: 1.46.12

**Comment by ssborbis** [comment] 2023-07-07 05:16
I was hoping this got fixed with some updated code, but I've seen it too.  I *think* the problem has to do with keeping the options page open in a background tab while interacting with CS menus, but I haven't gotten the bug consistently enough to check. I'll take another look now and see if anything stands out.

**Comment by ssborbis** [comment] 2023-07-07 05:43
I just pushed a possible fix to the master branch. Give it a try if you can normally get the bug to happen.

**Comment by ssborbis** [comment] 2023-07-29 17:21
v1.46.14 going up

**Comment by ssborbis** [comment] 2023-09-29 11:05
I think I finally tracked this issue down for good in 1.46.20. Reopen if you find otherwise, but it looks to be fixed.

**Closed by ssborbis** 2023-09-29 11:05 UTC
