### ISSUE TITLE
[Feature-Request] Quick-Menu Closing-Behaviour 

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#289] opened 2020-09-27 12:25 UTC
I would like the closing of the Quick-Menu to behave exactly like the closing of the regular FF-context-menu. I.E. it should close on a left click outside of the menu-area (which it does already) but without following links (in the case of that left-click happening on a link).

That would be great!

PS: Many thanks again for this wonderful addon! I am very new to it, but I am using it already all the time! Really great little helper! :-)

**Comment by ssborbis** [comment] 2020-09-27 17:07
Done

**Comment by ThomasSeeker** [comment] 2020-09-28 07:57
Wow! That was fast!

Looking forward to the next update then!   :-)

**Comment by ssborbis** [comment] 2020-09-29 05:24
I'll post here when a new release is out

**Comment by ssborbis** [comment] 2020-10-17 03:25
v1.27 live on AMO. ChromeStore in a day or 2

**Comment by ThomasSeeker** [comment] 2020-10-17 08:30
Ah wonderful! ... :-)

Thank you very much!

I wish you a great weekend!
Quick-Menu rocks!

**Comment by ThomasSeeker** [comment] 2020-10-17 10:00
Playing around and enjoying the new behaviour I also tried the youtube-page. And here it seems, that the links still get opened.

Example: https://www.youtube.com/watch?v=1HPCn3dOofk

Strange!

**Comment by ssborbis** [comment] 2020-10-17 17:21
Just on the youtube page or elsewhere?

**Comment by ThomasSeeker** [comment] 2020-10-17 18:25
On Facebook too, and also on the google-results-page.
But it does work on some pages though.

**Comment by ssborbis** [comment] 2020-10-17 20:17
Ah, I only accounted for anchor links. All those sites are using click events. I have a fix in mind. I'll issue a hotfix soon.

**Comment by ssborbis** [comment] 2020-10-17 20:38
Hotfix going up now to AMO. You'll need to enable `quickMenuPreventPageClicks` under the Advanced tab

`

**Comment by ThomasSeeker** [comment] 2020-10-17 21:00
Ahh ... that does the trick!
Wonderful!
Thank you very much!

**Comment by ssborbis** [comment] 2020-10-18 04:59
Sweet. I'll close this one out.

**Closed by ssborbis** 2020-10-18 04:59 UTC

**Comment by ssborbis** [comment] 2020-11-02 07:27
Just a heads up, there's a bug when using this option + opening the quick menu from an iframe. The no-click div gets left behind after closing the quick menu preventing mouse events in the iframe. . If you've been on some sites and lost your mouse after closing the qm, that's most likely the cause. I have a fix that I'm testing. I'll probably get a new release out in the next couple days.
