### ISSUE TITLE
Search result is opened in last tab

### ISSUE THREAD

**Issue by MW-J97** [ssborbis/ContextSearch-web-ext#379] opened 2021-10-08 08:50 UTC
Hi,
First, thank you so much for that great extension. 
I have a question, please. 
When I select any option like image or text and search it, the result comes at the end of the tabs not next the tab which I search from it e.g. if I have 5 tabs and I search in tab no. 2, the result will come after tab no. 5 not 2.
How can I make tab opens next to the original tab??
Thanks in advance.

**Comment by ssborbis** [comment] 2021-10-09 02:03
If you're using chrome, download the source and load it as an unpacked extension. If you're on firefox, use the latest alpha. It's from a few days ago.

**Comment by ssborbis** [comment] 2021-10-09 02:16
Walk me through a simple example of the problem so I can test on my rig. 

Also, are you using any other tab managers?

**Comment by minawaheed9697** [comment] 2021-10-09 02:22
I open many tabs and take one of them and search inside it for any text or image by quick menu, the result opens in the last tab although trying to enable and disable the `disableNewTabSorting` 
I use the original CS and disabled it and also use Toby mini, but didn't disable it.

**Comment by minawaheed9697** [comment] 2021-10-09 02:40
I reload tabs, reload chrome and disabled many extensions that can affect the CS, but nothing happen.
Please, do you test searching in first tabs or last tabs?? I mean, if you have 3 opened tabs, you search in 1st or 3rd tab as 3rd tab will open the result in next to parent tab.

**Comment by ssborbis** [comment] 2021-10-09 02:44
zip it and drag & drop into the comment box.

**Comment by minawaheed9697** [comment] 2021-10-09 02:51
[Config.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7314874/Config.zip)
That's config of native CS and dev one.

**Comment by ssborbis** [comment] 2021-10-09 02:55
How are you performing your searches? qm? context? which mouse button? etc

**Comment by minawaheed9697** [comment] 2021-10-09 03:00
Qm using keyboard "Ctrl" and choosing search engine and also by holding left mouse button

**Comment by minawaheed9697** [comment] 2021-10-09 03:01
Can it be an issue of chrome??

**Comment by minawaheed9697** [comment] 2021-10-09 04:18
I tried same steps on Edge browser and the same problem still occurs

**Comment by dnknn** [comment] 2021-10-09 12:16
I have no problems  at all here, the same version (1.28.1 of CS)

If want to troubleshoot the cause, I recommend testing these:

- Browser (fork of Chromium) (Self-definition of tab position)
	http://centbrowser.com/features.html#tabs

---------------------------------------------------------------------

- Extension tool,  I installed them, but they were not enabled (only temporarily enabled when needed)
	[SimpleTabOrder ](https://chrome.google.com/webstore/detail/cekafjbmkfofacenifehbglhmajimhjf)　　
	[Tab Position Customizer - Modified 　](https://chrome.google.com/webstore/detail/kkhcdbdhbmegbbhgmdhhpfmjhlhjlghp)

**Comment by minawaheed9697** [comment] 2021-10-09 12:57
Are you using chrome??

**Comment by minawaheed9697** [comment] 2021-10-09 14:50
I tried Centbrowser and has the same problem also. I toggled `disablenewtabsorting` on and off, still the same issue.

**Comment by ssborbis** [comment] 2021-10-09 21:33
new push in the dev repo

added advanced option `forceOpenReultsTabsAdjacent`

**Comment by minawaheed9697** [comment] 2021-10-10 02:23
Finally, it works. Thank you so much for your help.
Will it be added to the native version?? Or I have to use it as dev repo. I just want it to auto updated.

**Comment by minawaheed9697** [comment] 2021-10-10 04:27
Another thing I found, I make qm to open with Hold left mouse button, but sometimes when I just click a link or image it opens qm by click not hold. Is that an issue in dev repo or a setting must be done to solve it??

**Comment by ssborbis** [comment] 2021-10-10 04:59
@minawaheed9697 
> Will it be added to the native version

It will be in the next release

>  I make qm to open with Hold left mouse button, but sometimes when I just click a link or image or double click it, it opens qm. Is that an issue in dev repo or a setting must be done to solve it

From your config, I see you have the qm enabled for links and images. You might want to increase the hold timeout if it's triggering from a click. Raise the value of `quickMenuHoldTimeout` under advanced options. Try 500 or more

**Comment by minawaheed9697** [comment] 2021-10-10 05:07
Will it be soon??
I tried raising the value, but nothing happened. It shows qm also with fast double clicks, not even holding. 
I am so sorry for annoying you with those many questions.

**Comment by ssborbis** [comment] 2021-10-10 05:24
> I tried raising the value, but nothing happened.

Try setting it to something like 2000. You should definitely see a change. Also, be sure to click the save button on the advanced page. Changing those values doesn't automatically save settings.

**Comment by ssborbis** [comment] 2021-10-10 05:26
Can you send me your current config? I'm using your old config on chrome and things seem normal.

**Comment by minawaheed9697** [comment] 2021-10-10 05:28
[ContextSearchOptions_2021-10-10_052701.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7316901/ContextSearchOptions_2021-10-10_052701.zip)

**Comment by minawaheed9697** [comment] 2021-10-10 05:48
I think it's the same in chrome also, but sometimes it does this at the first time to QM to be opened on the site. 
Can it be fixed?? I can wait for the stable CS update if it'll be soon as I really love this extension 😍. I can't live without it 😂

**Comment by ssborbis** [comment] 2021-10-10 06:13
in the *dev* repo

**Comment by minawaheed9697** [comment] 2021-10-10 06:21
Yes, it works ❤️ Thank you so much for your great help. 
I hope the native release will be added soon.

**Closed as completed** 2021-10-10 06:25 UTC
