### ISSUE TITLE
1.0.1b9: Working with POST based search engines

### ISSUE THREAD

**Issue by MarkRH** [ssborbis/ContextSearch-web-ext#2] opened 2017-12-12 01:34 UTC
Well, I did notice on my latest import of my search engines that this one might not be compatible. It happens to be http://u.eq2wire.com/soe/item_search where I made search plugin for it at http://mycroftproject.com/search-engines.html?name=eq2 which does work when searching from the Search Bar.  Your extension sends the search terms out as GET variables which the site doesn't recognize.

Since the Search Bar can do it as a POST request, I would think it should be possible for an extension too as well or is this something beyond Web Extensions at this time?

Thanks for all your work.  It's the best one I've come across so far mainly due to how the icons don't load every time you look at the context menu.

**Comment by ssborbis** [comment] 2017-12-12 23:05
POST should be working in releases after 1.0.1b7.  Grab the latest release candidate here:

https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta

I'll update the git after this comment.

You'll have to re-import your search engines for POST to work.  I'll check your plugin to be sure it's compatible. I still flag POST search engines on import, but I've tested 2 engines so far and they're working.

**Comment by MarkRH** [comment] 2017-12-12 23:28
Haha, well, I just found out a new method to search at that site that doesn't require sending as a POST and changed the plugin I had at mycroftproject to use it instead.  It now sends requests as `https://u.eq2wire.com/soe/item_search_link/{search terms)/`

I'll keep the plugin like this since it's compatible with more browsers this way.

I'll make a new plugin for a different part of the site to see if the POST part works with your extension.

**Comment by ssborbis** [comment] 2017-12-12 23:46
I did use the earlier version of your plugin, the one that uses POST fyi.  It works

**Comment by MarkRH** [comment] 2017-12-12 23:52
I can't get it to work with 1.0.1b9 or 1.0.1rc1 from beta.  I made a new POST one doing a Recipe Search. http://mycroftproject.com/search-engines.html?name=u.eq2wire.com

Works from the Search Bar but doing Context Search always comes up with no results for the Recipe Search.  That Item search one, it would always me my previous search when I used from the context menu and not using the terms I had selected.

**Comment by MarkRH** [comment] 2017-12-12 23:56
Hmm, after restarting the browser, selecting the Recipe search from the Context Menu sends the request via GET and not POST: `http://u.eq2wire.com/recipe/recipe_search_results?recipe_name=Ceremonial%20Solstice%20Robe&submit=Search`

**Comment by ssborbis** [comment] 2017-12-13 00:26
I'll take a look

**Comment by ssborbis** [comment] 2017-12-13 01:16
That one works for me as well.

The expected behavior after clicking an icon or menu to search is to open a tab to http://u.eq2wire.com/recipe/recipe_search_results. After a pause while the javascript submits the POST form, you should see the results page for your search terms. I'm not sure why you're seeing different behavior. Do you have something installed that would block a hidden form submit? What version of FF are you using? What OS?

(edit2) The only way I know of right now to get a GET request for a POST search is if you're using a middle-click, or other non-left-click on a quickmenu icon, bypassing the POST methods and opening the <a href=...> directly. I haven't come up with a good way to avoid that yet aside from blocking the middle-click. It only fails for POST engines, but it will fail every time. That's one reason I kept the warnings when loading the search engines. Do you get the same behavior from the system context menu as the quick menu?

**Comment by MarkRH** [comment] 2017-12-13 01:34
I am using a normal Left-Click on the context sub-menu.  Using Firefox 57.0.2 in Windows 7.  Later on I'll try in a clean profile to rule out about:config, userChrome.css, or extension conflicts. In my current profile, both the Context Menu and the Icon popup version do the same thing.

**Comment by ssborbis** [comment] 2017-12-13 01:39
Strange.  I changed the mouse event in [RC2](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.0.1rc2) to mousedown instead of click.  That should get the same behavior from left and middle buttons.  You can try that, but if you're seeing this in RC1, it's probably something else.

**Comment by ssborbis** [comment] 2017-12-13 02:02
Ah, the .js isn't being injected when opening in a new window.  Is that how you're opening searches?

**Comment by ssborbis** [comment] 2017-12-13 05:49
Try [1.0.1rc5](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/beta?page=1#version-1.0.1rc5).  I rewrote the part of the POST handler.  There seemed to be some issues with async calls, and permissions.

**Comment by MarkRH** [comment] 2017-12-13 06:48
Yes, searches were being opened in new windows.  Will try the updated version.

**Comment by ssborbis** [comment] 2017-12-13 07:24
Great catch.  I'll look for which encodeURI is causing problems

**Comment by ssborbis** [comment] 2017-12-13 07:53
[rc7](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.0.1rc7)

**Comment by MarkRH** [comment] 2017-12-13 08:11
RC7 seems to work with the multiple word searches on POSTs now. :)

Thanks for all your work.

**Comment by ssborbis** [comment] 2017-12-13 08:16
I have another [open issue](https://github.com/ssborbis/ContextSearch-web-ext/issues/3) with URI encoding.  [RC8](https://addons.mozilla.org/en-US/firefox/addon/contextsearch-web-ext/versions/1.0.1rc8) fixed a problem with & in the search terms. 

These would never get fixed without feedback so thank you.

**Closed** 2017-12-13 09:39 UTC
