### ISSUE TITLE
Several issues after upgrading to v.1.31.3

### ISSUE THREAD

**Issue by sojusnik** [ssborbis/ContextSearch-web-ext#394] opened 2021-11-27 10:50 UTC
After upgrading to v.1.31.3 on Firefox 94 on Ubuntu 21.10, several issues appeared:

1. The quickmenu has now a gap at the top, while the bottom looks as it should be, see:
![grafik](https://user-images.githubusercontent.com/1245718/143677975-896af2eb-65cf-4a33-9db1-e20f0ae35dc6.png)

2. The ability to show folders in each own row in the quickmenu disappeared. There was an entry for that in the advanced settings, that now seems to be missing.

3. When summoning the quickmenu by holding the right mouse button on a selected text, then the quickmenu appears as before, but then the default context menu of Firefox appears, overlapping the quickmenu.

**Comment by ssborbis** [comment] 2021-11-27 14:36
1. I'll take a look. I may need your config to test
2. That setting was depreciated in favor of the group folder layout option 'block' which displays the contents of a folder in a colored div. Check CS Options -> Search Engines -> [ folder ] > Layout
3. If you're on an OS that opens the context menu on mousedown vs mouseup, you may need to enable `rightClickMenuOnMouseDownFix` in the advanced menu. This effectively hides the default context menu until you double-click the right button. The old way would lose some mouse clicks requiring a second attempt to open the menu. This way is a little more consistent.

**Comment by krisu5** [comment] 2021-11-27 15:12
> I'll take a look. I may need your config to test
It's `#addEngineBar` element FYI.

> The quickmenu has now a gap at the top, while the bottom looks as it should be
For workaround, gap is fixable with this CSS (add this to "general -> custom CSS" and enable the option too)
```
#addEngineBar { display: none !important; }
```

**Comment by sojusnik** [comment] 2021-11-28 11:16
> 2\. That setting was depreciated in favor of the group folder layout option 'block' which displays the contents of a folder in a colored div. Check CS Options -> Search Engines -> [ folder ] > Layout

The problem with this approach is, that with `block` you don't have folders any more, only the horizontal stripe (where you see the name of the folder), which you can't interact with (= using mouse actions), like you could with folders before.

> 3\. If you're on an OS that opens the context menu on mousedown vs mouseup, you may need to enable `rightClickMenuOnMouseDownFix` in the advanced menu. This effectively hides the default context menu until you double-click the right button. The old way would lose some mouse clicks requiring a second attempt to open the menu. This way is a little more consistent.

In my case this is a regression, because it worked perfectly well before v.1.3. I've never lost any clicks. Now with enabled `rightClickMenuOnMouseDownFix` you have to use the right mouse button twice to summon the default context menu, which goes against the default Firefox behaviour.

Don't get me wrong, I appreciate your effort constantly improving this wonderful add-on, but changing the default behaviour of opening the context menu is a major intervention, crippling the UX of Firefox.

**Comment by ssborbis** [comment] 2021-11-28 19:43
> In my case this is a regression, because it worked perfectly well before v.1.3. I've never lost any clicks.

You may not have missed clicks, or noticed, but other uses surely did. The way it's coded now gives the most consistent behavior between all platforms when using right-click opener methods. I'll see if there's a way to include the legacy method.

> The problem with this approach is, that with block you don't have folders any more, only the horizontal stripe (where you see the name of the folder), which you can't interact with (= using mouse actions), like you could with folders before

What interaction would you want? The contents should be displayed in the block.

The QM can display separators now. You could use them as a row break between inline-styled group folders.

> BTW, what is quickMenuAllowContextMenu changing? Played around with it, but can't spot a difference.

It disables some suppression of the default context menu when using right-mouse methods. It varies a bit based on OS and qm opening under the cursor or not.

**Comment by Ede123** [comment] 2021-11-28 19:59
> 3. When summoning the quickmenu by holding the right mouse button on a selected text, then the quickmenu appears as before, but then the default context menu of Firefox appears, overlapping the quickmenu.

I'm not quite sure I understand what the expected behavior is in version 1.3 but I noticed this as well. I'm on Windows, so the context menu is opened on mouseup. Was it expected that behavior changed in this case as well?

**Comment by ssborbis** [comment] 2021-11-28 20:09
> I'm not quite sure I understand what the expected behavior is in version 1.3 but I noticed this as well. I'm on Windows, so the context menu is opened on mouseup. Was it expected that behavior changed in this case as well?

Unless the option `quickMenuAllowContextMenu` is enabled, the default context menu should be suppressed on a context-menu-on-mouseup system like windows. Admittedly, I'm exclusively coding on linux these days, so if you guys are seeing both menus, something is up.

**Comment by Ede123** [comment] 2021-11-28 20:14
Hm, apparently I had to toggle both options to achieve previous behavior:
* `quickMenuAllowContextMenu` was on, I switched it off now
* `rightClickMenuOnMouseDownFix` was off, I switched it on now

**Comment by redactedscribe** [comment] 2021-11-28 21:47
I noticed the Firefox context menu opening on right-click long pressing too (when it didn't do so before). Not sure why the behaviour has changed, but turning off `quickMenuAllowContextMenu` made no difference: the context menu still pops up.

Enabling `rightClickMenuOnMouseDownFix` isn't needed on my system since the context menu only opens when mouse up is received, but if I _do_ enabled it, normal right-clicking stops being possible (but this is probably expected due my system being a on "mouse up" type, i.e. not meant for this setting).

Would be great if the context menu wouldn't pop up on long pressing right-click, `quickMenuAllowContextMenu` simply doesn't work.

**Comment by ssborbis** [comment] 2021-11-29 00:48
No wonder things are weird. The meaning of `quickMenuAllowContextMenu` got reversed when I moved it to the advanced menu. I'm putting up a signed version for testing. I'll drop it here to
[contextsearch_web_ext-1.31.4-an+fx.xpi.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7614796/contextsearch_web_ext-1.31.4-an%2Bfx.xpi.zip)
o.

See if that fixes any issues for anyone. Check that variable in the advanced options too. It should be off to prevent the extra menu.

**Comment by sojusnik** [comment] 2021-11-29 09:18
> > The problem with this approach is, that with block you don't have folders any more, only the horizontal stripe (where you see the name of the folder), which you can't interact with (= using mouse actions), like you could with folders before
> 
> What interaction would you want? The contents should be displayed in the block.

The same interaction, that was possible with the folder itself, not only its content, that is shown bellow the horizontal stripe.

> The QM can display separators now. You could use them as a row break between inline-styled group folders.

I've found the entry for separators in the search engine master, but when I add separators, then they just don't appear, neither in the search engine master, nor in the quick menu. `quickMenuHideSeparatorsInGrid` in the advanced options is disabled.

After updating to v.1.35, the quick menu works flawlessly again, the context menu does not appear any more. Thank you for fixing this. You're awesome!

**Comment by redactedscribe** [comment] 2021-11-29 13:22
> I'm putting up a signed version for testing.

Seems fixed in 1.31.4! (and too Copy to clipboard on links).

**Comment by ssborbis** [comment] 2021-11-29 15:28
Thanks to everyone contributing and pointing out these bugs. There's no way I can test all functions / configurations of this addon alone.

@sojusnik 

Looks like the function to add separators is broken. I'll patch that and see about adding back the row break option.

**Comment by ssborbis** [comment] 2021-11-29 22:19
@sojusnik 

groupFolderRowBreaks option is back in the advanced menu and 1.31.8 is live. It works differently than before, so keep an eye out for problems.

**Comment by sojusnik** [comment] 2021-11-29 23:58
@ssborbis 

Thanks for reimplementing `groupFolderRowBreaks`, this is very appreciated!

There's just one obstacle. After activating `groupFolderRowBreaks`, the quickmenu got some unused space, see
![grafik](https://user-images.githubusercontent.com/1245718/143960885-7d8c22b9-41d7-4942-94c6-80beccf9fee4.png)

Maximum number of rows to display on opening (grid view) is at 16.

> Looks like the function to add separators is broken.

Works now, thanks!

**Comment by redactedscribe** [comment] 2021-11-30 06:58
"Enable to show _show_ inline group folders as block elements" - double "show".

**Comment by sojusnik** [comment] 2021-11-30 08:39
Another typo:
![grafik](https://user-images.githubusercontent.com/1245718/144013458-728079f8-04eb-4ce9-88af-fa83b04ccd45.png)
Should be "Results".

**Comment by redactedscribe** [comment] 2021-11-30 09:00
I couldn't get `quickMenuTilesDraggable` to do anything, could be broken.

**Comment by ssborbis** [comment] 2021-11-30 15:03
@redactedscribe 

I think that option is depreciated now, in favor of the Edit tool.

**Comment by ssborbis** [comment] 2021-11-30 21:50
typos fixed in the repo

@sojusnik 

I rewrote the groupFolderRowBreaks code, and I think you're issue should be fixed. You seem to have a lot of inline group folders, so you're in a better position to test. In the dev repo

**Comment by ssborbis** [comment] 2021-11-30 22:02
@sojusnik I just noticed the row breaks aren't working in the toolbar menu. I'll keep you updated

**Comment by ssborbis** [comment] 2021-11-30 22:29
@sojusnik The problem was the toolbar menu was using an older, cached version of the stylesheet. I wonder how many problems that's caused over the versions.

**Comment by sojusnik** [comment] 2021-11-30 23:07
@ssborbis 
Got the new version! The unused area is now gone, but another small problem appeared:

I have 16 rows in my quick menu, but have to set "30" as maximum number of rows
![grafik](https://user-images.githubusercontent.com/1245718/144142367-cd95230b-317f-4eb5-b59a-ef29268543c6.png)
to see all rows at a glance, without them being collapsed.

**Comment by ssborbis** [comment] 2021-12-19 19:08
@sojusnik 

Has this at least improve at all? I know some things in the menu are being treated as a row that aren't rows of search engines ( group folders, separators, etc ). I, for example, have a setting of 10 rows in the config, but count 8 rows of search engines I have a block group folder and the 'more' button, which probably accounts for the 10. Best bet might be to resize the qm and forget what the config # is for now

**Comment by sojusnik** [comment] 2021-12-20 20:50
@ssborbis 
I still have 16 rows in my qm and only by having 30 as maximum row number shows they are shown at once. It's not a biggie, but maybe will confuse new members.

**Comment by ssborbis** [comment] 2021-12-20 20:58
@sojusnik 

Are you using `quickMenuHideSeparatorsInGrid` ? Do you have separators that are not shown?

**Comment by sojusnik** [comment] 2021-12-20 21:02
> @sojusnik
> 
> Are you using `quickMenuHideSeparatorsInGrid` ? Do you have separators that are not shown?

`quickMenuHideSeparatorsInGrid` is disabled and I don't have separators.

**Comment by ssborbis** [comment] 2021-12-20 21:56
@sojusnik 

Ok, so it's probably due to `groupFolderRowBreaks`

**Comment by ssborbis** [comment] 2021-12-20 23:59
@sojusnik 

The dev branch has a possible fix for that.

**Comment by redactedscribe** [comment] 2021-12-21 14:41
@ssborbis The copy to clipboard for _links_ seems to have broken again in recent versions (not sure which). v1.32.6

**Comment by sojusnik** [comment] 2021-12-21 19:51
> The dev branch has a possible fix for that.

Will test it when it's officially released, since I don't know how to install the dev version.

**Comment by ssborbis** [comment] 2021-12-21 21:39
@redactedscribe I re-opened #390 and put a fix in the dev repo

**Comment by redactedscribe** [comment] 2021-12-21 21:41
@ssborbis I'm supposed to build the web ext myself to test this, or is there an dev XPI somewhere?

**Comment by ssborbis** [comment] 2021-12-21 21:51
@redactedscribe If you want, you can install unpacked extensions temporarily in Firefox from `about:debugging`. 

Grab the source code from the development branch (https://github.com/ssborbis/ContextSearch-web-ext/archive/refs/heads/development.zip)

Always a good idea to export your CS config first.

open `about:debugging#/runtime/this-firefox` -> Load Temporary Addon -> browse the unzipped source code to /src/manifest.json

Close Firefox to revert to the old version.

**Comment by redactedscribe** [comment] 2021-12-21 22:50
@ssborbis Confirmed as fixed on the dev branch.

**Comment by ssborbis** [comment] 2022-01-21 04:24
Gonna close this out. If there are still unresolved issues, please reopen or make a new thread.

**Closed by ssborbis** 2022-01-21 04:24 UTC
