### ISSUE TITLE
✨Optimization Request:  Strictly define the single-letter Keyboard (Limit the modifier keys)  for Quick-Menu

### ISSUE THREAD

**Issue by dnknn** [ssborbis/ContextSearch-web-ext#327] opened 2021-03-06 18:45 UTC
> Finally report a problem..........

- ## ❥ **Expected/fixed behavior:**  ▼Focus on this picture▼
![213_07022033](https://user-images.githubusercontent.com/10995302/110216732-b4c29f00-7eeb-11eb-8bfa-f4694c13ab5d.png)

- ## 𐩕 **Steps to reproduce:**
　　　1. Just like the screenshot above, set a single letter hotkey, e.g. `E` 
　　　2. Select text on the page
　　　3. Press `Ctrl+E`  or `Alt+E` or `Shift+E` or  `Ctrl+Shift+E` or `Alt+Shift+E` or `Ctrl+Alt+E` or `Ctrl+Shift+Alt+E`
　　　4. Reproduce: using modifier keys will also trigger the function

----

- ## 💥 **Current "bugged" behavior:**
- For the ContextSearch web-ext itself, there will be a conflict, that is, a hotkey will trigger 2 functions at the same time. For example: 
　　　Find-bar set `Ctrl+Shift+E`
![213_07023118](https://user-images.githubusercontent.com/10995302/110217084-349d3900-7eed-11eb-8463-8226feac7a5e.png)
　　　Press `Ctrl+Shift+E` , I just want to open Find-bar,  but it also triggered Quick-Menu, obviously this is not the expected behavior.

- For the outside, If the external extension/script/or the website itself contains the modifier hotkeys of `E` , Obviously, when you press this modifier key when you select text  , it also means that Quick-Menu is triggered at the same time,

---
Therefore, can you add to Limit  the modifier keys  for Quick-Menu?
```js
// For example:
&& !event.ctrlKey && !event.shiftKey && !event.altKey
```

**Comment by hg42** [comment] 2021-03-06 23:03
why is ✨ ?

**Comment by ssborbis** [comment] 2021-03-07 00:44
> Therefore, can you add to Limit the modifier keys for Quick-Menu?
// For example:
&& !event.ctrlKey && !event.shiftKey && !event.altKey

Tricky, because some people use Ctrl as the hotkey.

I think the issue is, the qm hotkey is registered before the "shortcuts" ( see newer code ), so the event is propagating. I'll check it out.

**Comment by dnknn** [comment] 2021-03-07 00:59
> why is ✨ ?

^_^


> Tricky, because some people use Ctrl as the hotkey.

Can the `if {...}` method be used as a judgment ?

> I think the issue is, the qm hotkey is registered before the "shortcuts" ( see newer code ), so the event is propagating. I'll check it out.

Sorry, I don’t actually understand JavaScript code, only know a few snippets ...

**Comment by ssborbis** [comment] 2021-03-07 03:27
> Can the if {...} method be used as a judgment ?

No doubt. There may be a cleaner solution though. I'll look.

FYI, when opening the quick menu using a hotkey, there is a timeout of 250ms, so for now, you can hold your shortcut a little longer and the qm won't open

**Comment by ssborbis** [comment] 2021-03-07 11:58
check the repo, should be fixed

**Comment by dnknn** [comment] 2021-03-07 16:27
> check the repo, should be fixed

@ssborbis This problem has not been successfully fixed, it is still exactly the same as before...

**Comment by dnknn** [comment] 2021-03-07 16:30
> check the repo, should be fixed

@ssborbis This problem has not been successfully fixed, it is still exactly the same as before...

![image](https://user-images.githubusercontent.com/10995302/110247051-29a5df80-7fa5-11eb-929d-c3319b106292.png)

then , try to press `Alt+E` `Alt+Shift+E` `Ctrl+Alt+E` ... to reproduce

**Comment by ssborbis** [comment] 2021-03-08 01:00
Oh ok, I see. I just accounted for conflicting shortcuts.

**Comment by dnknn** [comment] 2021-03-08 01:23
> I just accounted for conflicting shortcuts.

I understand what you mean, you may not have seen the core issue of the issue at the time.

> * For the ContextSearch web-ext itself, there will be a conflict, that is, a hotkey will trigger 2 functions at the same time. For example:
>   　　　Find-bar set `Ctrl+Shift+E`
>   ![213_07023118](https://user-images.githubusercontent.com/10995302/110217084-349d3900-7eed-11eb-8463-8226feac7a5e.png)

This is just a random example, not the core problem, the core problem is that the modifier keys are not excluded...

**Comment by ssborbis** [comment] 2021-03-08 01:31
check the latest code to see if you're still having issues

**Comment by dnknn** [comment] 2021-03-08 01:54
👌 Thank you very much!!!  👍bugs was successfully fixed after tested!!💪

**Closed** 2021-03-08 01:54 UTC
