### ISSUE TITLE
Hide default 'search with' option in context menu/ put primary search engine outside submenu

### ISSUE THREAD

**Issue by m0001** [ssborbis/ContextSearch-web-ext#242] opened 2020-03-21 10:47 UTC
Hi, not sure if this is the right place for a feature request, apologies if it isn't. I'm trying to replicate behaviour from the contextsearch X addon for the pre- web extension firefox.

Currently, after selecting text and right clicking, I get two options- the default firefox 'search Google for Firefox' and then at the bottom of the menu is the contextsearch addon's submenu.

What I am trying to replicate is in the attached screenshot:
1- the default firefox search is hidden
2- and the addon menu has two functions: clicking the menu item searches using the default search engine (in this case google), but if you hover over it, it expands and you can select any of the others (in this case amazon/ wikipedia etc).

Not sure if possible or not- thought I would check.

Thanks for all your hard work

M

![ContextSearch](https://user-images.githubusercontent.com/62465462/77224839-5036f480-6b61-11ea-8ba9-0dfd6dd99fd3.png)

**Comment by ssborbis** [comment] 2020-03-21 19:33
This definitely the place for feature requests. 

But unless FF has made some changes I'm unaware of, the ones your asking for can't be done in this add-on. Since FF switched addons to the 'webextension' standard, making the code work with FF, Chrome, etc, many of the features of the previous generation no longer are available to developers. We are limited to a single menu entry, which can be a clickable object, or a tree of items / subfolders. Once a menu entry has children, the click event will always open the menu ( again, as far as I am aware ).

There was a user that managed to integrate this addon with his menu using a pre-webextensions plugin / addon of some kind that opened up all kinds of options.

Here's the thread https://github.com/ssborbis/ContextSearch-web-ext/issues/187

**Comment by m0001** [comment] 2020-03-22 09:53
Thanks for the quick reply - very clear!
Will check the thread out.

Cheers

**Comment by ssborbis** [comment] 2020-04-29 23:09
Duplicate of #187

**Closed** 2020-05-16 04:51 UTC
Labels: duplicate
