### ISSUE TITLE
all quick menus should be equal :-)

### ISSUE THREAD

**Issue by hg42** [ssborbis/ContextSearch-web-ext#94] opened 2018-08-17 03:35 UTC
One thing makes me wonder now and then:
The menu looks and behaves different when opened via toolbar button or as a context menu.

Probably, some things cannot be the same, but most parts could be exactly replicated.
E.g. number of columns, action buttons, setting button, ... come to mind.
I guess the popup could even use the same code. May be with little adjustments, because both ways start in differemt states (selection, mouse button).

What do you think?

Some reasoning:
My brain remembers positions of engines. To get optimal short mouse moves, I use a square format for the quick menu, which has more columns than the toolbar menu. They are also shifted because of the action buttons. So I find myself searching engines.

**Comment by ssborbis** [comment] 2018-08-17 04:35
I've thought the same thing but settled on keeping as close to the FF search bar as I could. Right now, the toolbar represents the complete list of search engines in the order of the search engines manager, hidden or not. The number of columns I set was meant to be similar to the FF search bar, which I believe changes the number of columns with the width of the toolbar.

> My brain remembers positions of engines. To get optimal short mouse moves, I use a square format for the quick menu, which has more columns than the toolbar menu. They are also shifted because of the action buttons. So I find myself searching engines.

That's the best argument for keeping the formatting the same between the Quick Menu and the Toolbar. What about a separate column setting for the Toolbar the user can set independent of the quick menu which defaults to the current column count ( 6 I think? ). I'd have to make the Toolbar respect show/hide or some users would see an altered layout. That probably should have been the default behavior anyway, but I was using the Toolbar as a way to access hidden engines for testing purposes.

Adding the columns option would be a trivial modification. I should probably start prepping for including the Manage With Bookmarks option for the Toolbar too.

**Comment by hg42** [comment] 2018-08-18 02:59
a setting for the columns should be ok.
However, the action buttoms will still shift the engine bittons.
I currently don't have access to my PC, not sure if this can already be solved in the settings?

**Comment by ssborbis** [comment] 2018-08-18 03:16
True, if the user has tools enabled, the layout would be different unless accounted for with empty cells. Maybe 3 options for Toolbar layout

* Quick Menu Layout (and compensate for tools)
* Single Column with Labels
* Custom Width (use gets column setting)

Seems like a `<select>` would be ok here and not add much bloat to Options

**Comment by hg42** [comment] 2018-08-18 08:48
I think in general, these two menus should either
* be equal and both use the same set of options
or
* have the same set of options, so they can be set to look equal

There were numerous times, I wanted to do something and realized it could only be done in the other menu. So, for me there is no difference.
However, I can understand if someone wants a different set of options, seeing the toolbar menu as extension to the (eventually shorter) quick menu.
E.g. one could have only icons, the other icpns with text for cases you don't remember which is what (which can also be done with a tooltip, but not as an overview, btw. I would also use the same columns in this case).

(again, from memory without access to the PC):

So may be, there could be two identically looking settings tabs, possibly with an option "same options for other menu", eventually disabling the other tab (but still visible). Clicking this option would copy all settings. So, you could make them equal and change some things afterwards. Alternatively a copy button would make this more explicit, but less automatic.

I like the thought to make them layout similar but with or without text.

Btw, the settings button is generally not much different from other action buttons.
The column shifting could be solved as ypu say by
* giving actions an own row (even if it's wrapping)
or easier
* by putting them at the end (not very good for a lot of engines).

Probably more ideas to come...

**Comment by ssborbis** [comment] 2018-08-21 05:43
I'm trying some things out, piling up caveats. I've got it set up to shift columns under certain conditions, but I need to think about changing the show/hide handling. It really needs to be reworked. Right now, the checkbox means "show/hide engines in the context menu (when NOT using bookmarks) and quick menu (when NOT using bookmarks) but do nothing to the toolbar menu". The checkbox is superseded by using bookmarks always. Not intuitive and really just a holdover from old versions.

I can:
1. Include a checkbox column for
     * show/hide in context menu
     * show/hide in quick menu
     * show/hide in toolbar menu

and have show/hide supersede bookmarks

-or-

2. Include a checkmark column for
     * show/hide in context menu
     * show/hide in quick menu

use the quick menu show/hide for toolbar as well and have show/hide supersede bookmarks

-or-

3. Include a checkmark column for
     * show/hide in context menu
     * show/hide in quick menu

leave all search engines visible to the toolbar and have show/hide supersede bookmarks

Ideally for me, the dev, users would set one list and use that for all 3 menus. But seeing as the quick menu was intended to be used as a compact speed dial and not include all installed search engines, this seems impractical. With the addition of managing with bookmarks, it is possible to get a large search engine list in a small form factor, but I can't expect all users to use bookmarks unless I add the Bookmarks permission as mandatory and write a custom tree viewer for managing search engines and folders.

The way I see it, the context menu / toolbar menu / quick menu cannot be expected to be equal. There needs to be a way to have some degree of customization. What I have now is in no way ideal. It needs an overhaul. I'm just not sure how it should be done.

> There were numerous times, I wanted to do something and realized it could only be done in the other menu. So, for me there is no difference.

I thought the Toolbar Search and Quick Menu shared most functionality. What could you do with one but not the other?

**Comment by hg42** [comment] 2018-08-24 17:01
sorry for answering late, I took a chance to go on a short vacation.

last (easiest) question first:
> I thought the Toolbar Search and Quick Menu shared most functionality. What could you do with one but not the other?

the quick menu contains the action buttons (open as link etc.) at the top (shifting the engines) and no settings at the bottom, vice versa on the toolbar menu

up to now I wasn't very interested in the bookmarks option, so I didn't notice that putting engines in a bookmarks folder would allow to manage them there and also allow folders.
I have to investigate if and how I want to use this. May be the folders are useful, though they need a second click.

From a developer's view, I would tend to eliminate duplicated functionality.
If it's a kind of duplication with reuse of most of the code, then the disadvantages are usually small (something like opening the same menu from toolbar or context menu).
However, if the dupes differ in significant parts, it's more work to keep everything in sync and it's also difficult for a user to understand what's the difference and to configure the variants to be useful.

Check boxes to select which engines are shown on which menus seems to be simple enough.
On the other side, if most users tend to enable all engines on all kinds of menus, the check boxes will be inconvenient (so they should at least be enabled by default).

From a user's view, I like to choose the best option, where "best" may be different dependent on use cases or individual preferences.

The art lies in finding a good balance.
It's similar for programming languages, **python**: there should be only one way to do it ; **ruby**: why not offer variants of interfaces borrowed from smalltalk/perl/etc.? use different methods for different aspects.

What makes the quick menu "quick"?
* less engines to prepare and draw?
  * in fact the toolbar menu is quicker for me, because I use long press for the context menu, because I want the standard context menu on short press (right mouse button), unless all it's functionality would be incorporated in the quick menu (will not happen)
  * I think there is no significant delay otherwise
* shorter list of engines to be remembered?
  * I am purposely placing the most used engines at the top, so it doesn't matter if there are more below

Thrown together, I don't see a reason (at least for me), why the quick menu should only have a selection of engines.

I found that some of my differences between toolbar and context menus originated from the management via bookmarks. When I disabled bookmarks *and* edited some engine in the options, the engines started to be ordered identically on both menus. Now, after disabling the action buttons and adjusting the number of columns of the quick menu to match the toolbar menu, the menus look quite similar (however the buttons are wider (non-square) in the toolbar menu).

**Comment by hg42** [comment] 2018-08-24 17:52
now that I tested folders, I want them everywhere :-)
At least the folders could be flattened (their items inserted instead of the folders) in the toolbar list.
From my point of view, the toolbar menu and context submenu should definitely follow the same order. Any objections?

The folders would be even more useful in the context submenu, where they could be shown as a submenu, which would make the whole menu shorter.
The toolbar menu could also the same simple menu with submenus, eliminating the need for the whole discussion above. It is reasonable to have a single column menu with icons and text and submenus to keep it shorter. If a user isn't sure about an icon in the quick menu or if there could be better engines or something similar, it is good to have a more descriptive representation on the toolbar (or the context submenu).

The folders/submenus allow to make mouse movements much shorter and also decrease the number of items to remember for each section. It is also possible to divide top level engines by folders. E.g. I have a video folder with everything about videos (e.g. imdb) followed by top level youtube and amazon video for the usual cases.

I think, users that only use a few search engines, don't need to know how to manage the menus via bookmarks, while power users with a lot of engines will probably appreciate the management via bookmarks. Chances are, they already know well, how to manage bookmarks.

Btw. folders don't react on button release. Actually it would be most convenient, if they would open on hover, so a press-hold-hover-move-release sequence could select an engine in a submenu in a single stroke. The behavior of a standard GTK menu seems to be optimal and works when started with button pressed or without.

I think, the look of a folder is too cluttered (3D icon + shadowed text). I have difficulties to identify them fast enough.
I guess a folder icon with simple black label below would be better. Or may be a full size folder icon in light yellow with black label inside.
I can produce examples if you want.

**Comment by hg42** [comment] 2018-08-24 18:01
> My only reservation is some users losing some funcitonality

yes, may be some warning message about upcoming changes could ask users to discuss on a specific board or thread e.g. in google+ or something similar. Ideally something without login...
Or, I often thought of a poll mechanism (a survey?), but never investigated what would be possible.

Developers sometimes stick to assumed requirements that never existed. It's difficult to decide without feedback.

**Comment by hg42** [comment] 2018-08-24 18:15
`Manage With Bookmarks` has several advantages:
* all bookmark tools can be used
  * better managers
  * managing directly in the menu (one reason I would like to have context search folder in top level bookmark menu)
  * find duplicates
  * check if still valid
  * import/export
  * sync
* users know how to use it

**Comment by ssborbis** [comment] 2018-08-24 18:42
> From my point of view, the toolbar menu and context submenu should definitely follow the same order. Any objections?

That looks to be where things are headed.

> The folders would be even more useful in the context submenu, where they could be shown as a submenu, which would make the whole menu shorter.

I'm surprised you didn't migrate to `Manage With Bookmarks` already. It definitely has some advantages.

> The toolbar menu could also the same simple menu with submenus, eliminating the need for the whole discussion above.

Yep. I'm prepping for those changes.

> Btw. folders don't react on button release. 

Hmm, yeah I guess I didn't attach that to mouseup like the other search functions. I'll change that.

> Actually it would be most convenient, if they would open on hover, so a press-hold-hover-move-release sequence could select an engine in a submenu in a single stroke.

Open on hover is doable

> I think, the look of a folder is too cluttered 

Getting a good label is a huge pain given the limited size. I'll take any improvement.

> Manage With Bookmarks has several advantages:

Bookmarks for use with ContextSearch still need to be added through the addon manager. Only bookmarklets can be added separately and understood by ContextSearch. That's why I think a bookmarks-like manager in place of the current manager would be best. Everything in one place for all users. I have code to import current users' bookmarks into the new format, including bookmarklets.

I think a detailed notice page that opens on the big update can migrate users over to the new format.

As I see it, there will be 3 types of users

1. User does not use Manage With Bookmarks for either menu
Roll them over to the format without any changes. No notice required

2. User uses Manage With Bookmarks for both menus
Roll them over to the format without any changes and inform of the new manager.

3. User uses a mix of Manage With Bookmarks and built-in manager
Inform of changes and prompt for which setting to use for all menus and discard the other.

**Comment by hg42** [comment] 2018-08-24 21:08
> I'm surprised you didn't migrate to Manage With Bookmarks already. It definitely has some advantages.

I had this enabled from the beginning, but wasn't aware it's for **managing** and would also allow folders.

> Getting a good label is a huge pain given the limited size. I'll take any improvement.

yes, I hope, a label without shadow can be more condensed. The easiest design could simply use a light yellow background for folders.

> Bookmarks for use with ContextSearch still need to be added through the addon manager.
> ...

I understand... but it seems to be a lot of work.

> As I see it, there will be 3 types of users

as a user, I think it's worth to invest some time, if I can get improvements.
Ideally, I would like to be warned **before** upgrading, because at this point I may not have time to make such changes, so I would delay the upgrade in this case until I get enough spare time.
But I guess it's not possible to warn before upgrading? Especially if auto upgrade is enabled...
In case of additional permissions the upgrade is delayed until the user clicks on the warning, but I think this would be a hack and the warning text seems to be determined by Firefox.

**Comment by hg42** [comment] 2018-08-24 23:05
oh, the context menu already has folders, awesome...
must have changed since the last release?

a simple design for folders in quick menu:
![image](https://user-images.githubusercontent.com/4707597/44611662-d0209f80-a802-11e8-871b-1b725d93b6c1.png)

**Comment by hg42** [comment] 2018-08-24 23:16
would be nice to have line breaks...
each line could be a group with folders as kind of overflow.
Overflow could even be automatic as "..." folder (but not for me).

**Comment by hg42** [comment] 2018-08-24 23:33
```
#quickMenuElement DIV .folderLabel {
	font-size:6pt;
	line-height:1em;
	padding:1px;
	font-family:Arial;
	color: blue;
	background: #ffffcc;
	/*
	font-weight:bold;
	color: white;
	text-shadow:-1px -1px 0 #000,1px -1px 0 #000,-1px 1px 0 #000,1px 1px 0 #000;
	*/
	text-align:center;
	display:table-cell;
	vertical-align:middle;
	height:30px;
	overflow:hidden;
	white-space:normal;
	text-align:center;
	width:30px;
}
#quickMenuElement DIV .folderLabel:hover {
	background: #ddecd7;
}

```

**Comment by ssborbis** [comment] 2018-08-26 06:14
That's definitely more legible. I've got a few ideas to fancy it up a bit. I'll post a screenshot when I get there, but there's a ton of backend to do first. Making progress

**Comment by ssborbis** [comment] 2018-10-18 22:07
Just uploaded a bit update to the repo. See #99

**Comment by ssborbis** [comment] 2018-11-01 06:44
I think the latest update implements your suggestions pretty well. Gonna close this thread for now.

**Closed by ssborbis** 2018-11-01 06:44 UTC
