### ISSUE TITLE
Size of quick context menu changes according to page zoom size.

### ISSUE THREAD

**Issue by streetwolf** [ssborbis/ContextSearch-web-ext#141] opened 2019-01-08 15:02 UTC
Depending on the zoom amount for a page the quick context menu will change.  I've attached two screenshots.  One is set at 100% as you can see by the icon on the top right.  This produces a large menu.   The other one is set to a zoom of 80% and is smaller.  Keep in mind that my DPI is set to 200 , so 100 is 200dpi while a zoom of 80% is really 160 dpi.  Can this behavior be fixed?

![large](https://user-images.githubusercontent.com/410799/50838474-1139cc00-132c-11e9-9f7d-e0b8aa646b7b.png)
![small](https://user-images.githubusercontent.com/410799/50838480-13038f80-132c-11e9-8ceb-11448245f34c.png)

**Comment by ssborbis** [comment] 2019-01-08 15:21
That's odd. I have code to compensate for page zoom, at least for the zoom level at the time of opening the menu. The menu should remain at a constant size regardless of zoom, with the exception of changing the zoom while the menu is open. I dont have any zoom change listener. What's your platform? All zoom data is pulled from `window.devicePixelRatio`.

**Comment by streetwolf** [comment] 2019-01-08 15:25
I’m running Fx66 Nightly and Windows 10.  As stated, I run with an OS DPI of 200% because I have a 32 inch 4K monitor. Fx uses the OS dpi.  I use an addon called Zoom Page WE to control the size of pages because some are either to small or to big.

-----
Gary

________________________________

**Comment by streetwolf** [comment] 2019-01-08 15:32
Disabled it and have the same issue.  Keep in mind that even though it is disabled if you look at the Fx built in zoom feature the size is still retained.  I suspect that using Fx’s zoom at different sizes for pages might also exhibit the problem.

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-08 15:43
Ah i get you now. I'm afk on mobile atm and probably won't be able to test until tomorrow. I have been using the latest release, FF64.? on a 4k win10 with the standard dpi without issue but never tested nonstandard zoom at the OS level. If there's no programmatical fix, I'll add an option to compensate.

**Comment by streetwolf** [comment] 2019-01-08 15:48
Sounds great.  You are always on top of issues which is very commendable.

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-09 07:32
I tried setting windows scaling through Settings -> Display Settings -> Scale & Layout -> 200% but couldn't reproduce your issue. Quick menu size stayed consistent. I'll try the nightly next.

50% page zoom
![50](https://user-images.githubusercontent.com/24310997/50883609-30793d80-13ae-11e9-838d-24c485b92705.png)

200% page zoom
![200](https://user-images.githubusercontent.com/24310997/50883622-37a04b80-13ae-11e9-9535-704fa19cac23.png)

**Comment by ssborbis** [comment] 2019-01-09 07:40
No change in the nightly. Have you tested with a fresh profile?

**Comment by streetwolf** [comment] 2019-01-09 12:24
Just tried CS on a new profile.  cnn.com produces a Quick Menu far larger than the other sites I also tried it on.  CS is the only add-on btw.  I used Fx’s zoom feature and that had no affect on the size of the QM.  Is there something about cnn.com?

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-09 12:33
Yep, CNN has some css overriding the scale attribute. I'll see what I can do

**Comment by streetwolf** [comment] 2019-01-09 12:34
Other sites must also do the same thing.  Will your fix cover all these types of sites?

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-09 12:42
Depends. I thought setting `{ all:unset }` would clear any css overrides, but I guess I was wrong. Some sites will use javascript to apply styles to elements which makes it really difficult to account for. For the most part, wrapping the addon UI in an iframe takes care of most conflicts, but not all. I'll throw some stuff against the wall.

Here's what CNN is using that messes up the scaling.

```
body > :not(.nav):not(.tooltip) {
    -webkit-transform: none !important;
        transform: none;
    -ms-transform: none !important;
    transform: none !important;
}
```

**Comment by streetwolf** [comment] 2019-01-09 12:45
Cnn.com does a lot of nutty stuff.  I go there often for my news so I am not 100% sure that I see this problem on other sites.  I’ll make a note if other sites behave the same way.

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-10 20:32
I haven't been able to find a general fix for websites overriding styles with !important other than adding !important tags to all my CSS. That's pretty messy. Apparently it's a problem for other devs too. It's unfortunate the webextensions API doesn't have an option to supersede the normal CSS order or precedence. I'll play around and see if bulk !important tagging causes any problems. If not I'll just do that and call it a day.

**Comment by ssborbis** [comment] 2019-01-27 20:40
@streetwolf 

Just released 1.9.5. I got explicit on the transform rule for CS iframes so the scaling should be fixed for CNN and other sites that use that particular trick

**Comment by streetwolf** [comment] 2019-01-27 22:16
Great new.  I found another anomaly at msn.com.  Highlight some text and bring up the Quick Menu via right click.  The QM appears much lower and as soon as you let go of the mouse button you get the default context menu appearing over the QM.  If the text selected is near the bottom of your screen things might happen differently.

-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-27 22:42
I'm not having that issue on msn.com. What's the url you're on?

**Comment by streetwolf** [comment] 2019-01-27 22:45
Try https://www.msn.com/en-us/news/politics/trump-advisers-lied-over-and-over-again-mueller-says-the-question-is-why/ar-BBSN7ef



-----
Gary

________________________________

**Comment by ssborbis** [comment] 2019-01-27 22:48
Works ok for me. What are your QM settings for opening (position, offset, searchbar position, tools position)?

**Comment by ssborbis** [comment] 2019-01-27 22:56
ah shit, forgot about your DPI settings. Lemme adjust and test again.

**Comment by streetwolf** [comment] 2019-01-27 23:03
DPI strikes again.  I’ll await your fix.

-----
Gary

________________________________

**Closed** 2022-01-02 10:05 UTC
