### ISSUE TITLE
Changes for 1.9.8 - released

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#173] opened 2019-04-09 00:52 UTC
- findbar can be opened / closed in all tabs at once
- findbar settings are saved on change
- separate mark options for findbar and search highlighting
- quickmenu tools can be displaced as a separate toolbar
- selected text converts newlines to spaces
- hotkeys for sidebar and findbar use KeyboardEvent.key vs KeyboardEvent.keyCode
- context menu item "Add Custom Search" listener reworked for context-menu-on-mousedown environments
- clear search history button fixed
- disabling option to display history in search results not working when history array was not empty fixed
- bookmarklets variable CS_searchTerms uses raw selected text vs newline trimmed search bar value
- quick menu closing on resize fix

**Comment by hg42** [comment] 2019-04-10 11:15
after being offline (from contextsearch) for some time...I'll think I provide some collected feedback to these points (apart from eventual more specific comments on issues).

> findbar can be opened / closed in all tabs at once

my favorite, a big thanks for that...
I was just going to create a new issue, because I found myself closing findbars all the time when using it with my 50++ tabs  :-)

> quickmenu tools can be displaced as a separate toolbar

doesn't make much sense in my quickmenu layout, but might be useful with more tools (I will add an feature request issue)

> selected text converts newlines to spaces

it might also help to remove other characters, but I'm not sure about special search engines. I guess it's better to leave the responsibility to the engine. It would be good for some dumb search engines. This could be an option for each search engine.

> hotkeys for sidebar and findbar use KeyboardEvent.key vs KeyboardEvent.keyCode

nice, this works well for all the keys I tried
(though I would style the "Unidentified" button only as a text to be more clear that it's not a key)

> context menu item "Add Custom Search"

always displays the correct term (as far as I have looked at it)

thanks again, this solves nearly everything I had on my queue (in my head). The only one remaining seems to be the empty toolbar menu.

**Comment by ssborbis** [comment] 2019-04-10 20:22
> thanks again, this solves nearly everything I had on my queue (in my head). The only one remaining seems to be the empty toolbar menu.

I just cannot get that glitch. I need to test more on 'nix.

@hg42 If you're using the latest push, I've encountered a bug which recursively loops the highlighting code and can cause 100% cpu. I'm going to issue a new push that temporarily disables marking until I can find the cause

**Comment by hg42** [comment] 2019-04-13 23:35
I guess one of the main differences between our configuration is probably the count of engines...I currently have 107 entries (including folders).

Also, my CPU is kind of old, so it might be somewhat slow (even if the clock speed might look comparable):
Processor		: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
Memory		: 8052MB (3177MB used)
Operating System		: Debian GNU/Linux buster/sid

the same for the display, the GPU is integrated in the CPU, so it is from the same stone age :-)
Resolution		: 4096x1152 pixels
OpenGL Renderer		: Mesa DRI Intel(R) Sandybridge Desktop 

So, did you ever test with many entries?
Probably, if you want to test, you might need much more entries than me, because of faster graphics etc. A CPU or GPU speed comparison table might give a hint.

**Comment by ssborbis** [comment] 2019-04-13 23:55
@hg42 

I've got about 90 engines in several folders ( most in the root folder ). I've tried setting some of the window resize functions in timeouts to simulate slower machines, done extensive testing in virtualbox systems (win7, ubuntu) that lower the processing power, etc but I can't reproduce the bug.

I've noticed FF does a strange thing in that it generates the toolbar menu/page on mousedown of the browser_action button but doesn't show the window until mouseup. If I hold the button down for a sec before releasing, the tile resizing function for low column counts is finished before the window opens. I don't know how consistently you can produce the bug, but have you noticed your click speed on the toolbar button to have any effect? Do you get any errors in the extension debugging console when it glitches? I can spam the toolbar button and occasionally get a `Unchecked lastError value: Error: sender.page is undefined include.preload.js:546 Error: page is undefined` message but no glitchy small window.

**Comment by ssborbis** [comment] 2019-04-14 00:06
@hg42 
I checked cpu benchmarks, and our CPUs are essentially the same single-thread speed, and you have 2 more cores than I do (G4560).

https://www.cpubenchmark.net/compare/Intel-i5-2500K-vs-Intel-Pentium-G4560/804vs2925

I have a modest gpu though (gtx 650ti) , so I've got more rendering power. That could account for the differences.

**Comment by hg42** [comment] 2019-04-14 00:07
That's funny, independently from your comment above, I tested my click behavior again.

And yes (I think I already reported something like this) it's very clear that it has to do with the way I click.

If I always hold the mouse button may be about 0.5 sec the menu always works.
But my usual click is very short. The button is probably released before the menu had any chance to open.

I don't know an extension console, how do I get this? (I onbly know Web Console and Browser Console, both do not give me errors related to the behavior)

**Comment by hg42** [comment] 2019-04-14 00:10
nice to know that I'm not totally off the road with my CPU :-)
The influence of GPUs is sometimes weird, because 2D is not always affected by the 3D engines. But I think integrated GPUs are usually quite slow.

**Comment by ssborbis** [comment] 2019-04-14 00:19
> And yes (I think I already reported something like this) it's very clear that it has to do with the way I click.

I knew someone had mentioned it, but I didn't noticed the page rendering was effected so dramatically by it until recently.

> I don't know an extension console, how do I get this?

If you go to about:debugging, enable debugging and click "debug" for this addon, you will be prompted to display the addon debugging window. That's where all the background logging and errors go. I'm guessing this bug isn't throwing errors but worth a look.

**Comment by hg42** [comment] 2019-04-14 00:30
hmm, I always have CS in about:debugging, but there is only an inspect button, ok, there it is...
interesting, I have probably seen the extension debugging before, but I didn't notice that it's not the same contents like the global debugging window. It looks like a filtered view (only the extension...), but the messages are not a subset of the global console.

There are a few messages for each popup of the menu, but they don't differ between empty or filled.

**Comment by hg42** [comment] 2019-04-14 00:33
hmm, in which file do I find the toolbar menu handlers?
I would like to insert some delay to force every click to be "too fast".

**Comment by ssborbis** [comment] 2019-04-14 00:41
searchbar.js has the handlers for the sidebar and toolbar menus. The content resize function for after the window is rendered is `toolBarResize()`

I'm going to try limiting my gpu for testing.

**Comment by ssborbis** [comment] 2019-04-14 01:13
Running ubuntu in a vbox with 32MB of gpu memory with 2300+ search engine tiles and still no glitches.

**Comment by hg42** [comment] 2019-04-14 01:35
I changed the height calculation to this:
```
			var wih = window.innerHeight;
			console.log("wih = " + wih);
			var sbh = sb.getBoundingClientRect().height;
			console.log("sbh = " + sbh);
			var sgh = sg.getBoundingClientRect().height;
			console.log("sgh = " + sgh);
			var tbh = tb.getBoundingClientRect().height;
			console.log("tbh = " + tbh);
			var mbh = mb.getBoundingClientRect().height;
			console.log("mbh = " + wih);
			h = wih - ( sbh + sgh + tbh + mbh );
			qm.style.height = h + "px";
			console.log("sum: " + h);
```

a "good" menu:
```
wih = 600 searchbar.js:356:12
sbh = 30 searchbar.js:358:12
sgh = 2 searchbar.js:360:12
tbh = 24 searchbar.js:362:12
mbh = 24 searchbar.js:364:12
sum: 520 searchbar.js:368:12
```

an empty menu:
```
wih = 80 searchbar.js:356:12
sbh = 30 searchbar.js:358:12
sgh = 2 searchbar.js:360:12
tbh = 24 searchbar.js:362:12
mbh = 24 searchbar.js:364:12
sum: 0 searchbar.js:368:12
```

so the problem is the window.innerHeight
if I change mbh to some big constant like 1000 or 9999 or even -9999 it works all the time.
With 500 I get sum=44 and there is are two result states again, but the menu isn't empty (not size 0).
So I think it never was really empty like I thought.
If entering some characters the suggestions are shown and the menu area is actually resized, but not to the correct size (I get sum=9).

**Comment by hg42** [comment] 2019-04-14 01:45
> if I change mbh to some big constant like 1000 or 9999 or even -9999 it works all the time.

well, this was actually my first test...of course it's easier and more logical to set wih to some big constant...

**Comment by ssborbis** [comment] 2019-04-14 02:03
What is the initial value of `qm.getBoundingClientRect().height` before setting height?

Maybe I need to set  `qm.style.overflow = 'visible'` immediately after the menu is built and change to 'hidden' after the window.innerHeight < qm height check.

**Comment by hg42** [comment] 2019-04-14 02:29
```
wih = 600 searchbar.js:356:12
sbh = 30 searchbar.js:358:12
sgh = 2 searchbar.js:360:12
tbh = 24 searchbar.js:362:12
mbh = 24 searchbar.js:364:12
qmh = 980 searchbar.js:366:12
qmsh = 980 searchbar.js:367:12 (scrollHeight)
sum: 520 searchbar.js:370:12
```
vs.
```
wih = 80 searchbar.js:356:12
sbh = 30 searchbar.js:358:12
sgh = 2 searchbar.js:360:12
tbh = 24 searchbar.js:362:12
mbh = 24 searchbar.js:364:12
qmh = 980 searchbar.js:366:12
qmsh = 980 searchbar.js:367:12 (scrollHeight)
sum: 0 searchbar.js:370:12
```
​

**Comment by hg42** [comment] 2019-04-14 02:31
> change to 'hidden'

isn't it 'scroll' ?

**Comment by ssborbis** [comment] 2019-04-14 02:38
just found the css. It's 'auto'

**Comment by ssborbis** [comment] 2019-04-14 02:47
What happens if you check for window.innerHeight < 600 and force the qm height accordingly? Does the window adjust?

```
if ( window.innerHeight < document.documentElement.scrollHeight ) {
			
			qm.style.height = ( (window.innerHeight < 600 && qm.scrollHeight > 520) ? 600 : window.innerHeight ) - ( sb.getBoundingClientRect().height + sg.getBoundingClientRect().height + tb.getBoundingClientRect().height + mb.getBoundingClientRect().height ) + "px";
			
		//	qm.style.height = window.innerHeight - ( sb.getBoundingClientRect().height + sg.getBoundingClientRect().height + tb.getBoundingClientRect().height + mb.getBoundingClientRect().height ) + "px";
		}
```

**Comment by hg42** [comment] 2019-04-14 02:58
> What happens if you check for window.innerHeight < 600 and force the qm height accordingly? Does the window adjust?

yes...
I added a print and in the case of an empty menu it says it's adjusting to 600 and creates an completely identical result like in the "good" case (as far as I can see).

**Comment by ssborbis** [comment] 2019-04-14 03:09
Ok, I'll just run that check then for FF users. Instead of hard-coding the 600 for window.innerHeight, it might  work just as well to check window.innerHeight === sumHeight in case some platforms have a different maxWindowHeight.

I'll tidy up a few things and make a push in a few

**Comment by ssborbis** [comment] 2019-04-14 03:24
Fix is in the repo along with a few additions

```
open in sidebar option
toolbar fix
search in all tabs added to findbar
add custom search fix for forms that require a test search to parse the url for getting a template
```

**Comment by hg42** [comment] 2019-04-14 03:33
I think, if you set a high value (higher than document height or similar), it will always be limited to the possible height or any maximum set by firefox.
I never understood why firefox has a height limit. Scrolling is always worse than a full height menu.

**Comment by hg42** [comment] 2019-04-14 03:38
jepp, it works

**Comment by ssborbis** [comment] 2019-04-14 03:42
It's not just firefox. I think chrome has the same limit. It would be so nice to have a bit of control over the window size.

> jepp, it works

Woohoo, only took a few months. Thanks for troubleshooting with me.

**Comment by hg42** [comment] 2019-04-14 04:11
thanks for your patience :-)
the best developers are those that don't give up...

according to the limit...600px...I am quite sure it is a fixed number. I think that's the saddest part of it...especially for a software like this.
Think of big screens or high densities, it will definitely become a problem at some point.
There are definitely better ways to solve this and they are all easy with css. E.g. using a real length unit (mm) or relative to font height...lot's of possibilities.
This must have been written by a 4 year old child...

**Comment by ssborbis** [comment] 2019-04-14 04:36
Yeah they didn't spend much time on the browser_action window. Looks like the max size is 800x600 regardless of screen or browser size. I don't know how much other add-ons rely on it, so maybe it's not a common enough issue for the moz team to worry about.

**Closed** 2019-04-19 02:09 UTC
