### ISSUE TITLE
Moving Entries into an empty folder not possible

### ISSUE THREAD

**Issue by ThomasSeeker** [ssborbis/ContextSearch-web-ext#287] opened 2020-09-21 09:59 UTC
Hey there, 

I guess, this is a bug. In my case and with FF 80 it was not possible within the Search-engines-manager to move entries into a newly created empty folder. 

Workaround: Do the moving from within the quick-menu.

Once the folder has at least one entry ... further entries can be moved into it without issue.

Best greetings,
Thomas

**Comment by ssborbis** [comment] 2020-09-22 01:03
I'm not seeing this issue. Any errors in the console?

**Comment by ssborbis** [comment] 2020-09-22 01:06
My method of testing is 

1. Right Click -> New Folder
2. Drag an engine onto the New Folder label

![move](https://user-images.githubusercontent.com/24310997/93835778-f2858100-fc45-11ea-8599-e81058c87266.gif)

**Comment by ThomasSeeker** [comment] 2020-09-22 09:15
Yes, the same method of testing I use. In my case the folder background doesn't even turn blue while dragging an engine over it.

How can I run this in the console? ... or get a console output?

**Comment by ssborbis** [comment] 2020-09-24 03:35
In FF, CTRL+SHIFT+K opens the console.

If you don't see any errors, send me your config and I'll take a look ssborbis@gmail.com

**Comment by ThomasSeeker** [comment] 2020-09-24 08:02
No errors in the console.
I send you an email.

**Comment by ssborbis** [comment] 2020-09-25 07:00
I tried your config and was able to move engines into empty folders without issue. I'll try on another machine tomorrow. 

I assume you're using the latest addon release ~ v1.26   What OS are you on? Windows? Linux?

Do you have any other addons installed that could interfere?

Since you have a workaround, I get that it's not a huge issue but it would be nice to figure out the cause.

**Comment by ssborbis** [comment] 2021-01-23 08:34
should be fixed in v1.28. I'll re-open if otherwise

**Closed by ssborbis** 2021-01-23 08:34 UTC
